[features]
seeds = false
skip-lint = false
[programs.devnet]
carbon_contract = "2sH2Q2kcFvWpxjXqv78THttyfVKS25eNFvuD3vaj6BiN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/le/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
